apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default-project
  namespace: argocd
spec:
  description: Default project
  sourceRepos:
    - 'https://github.com/clear-route/local-monitoring-stack.git'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'ghcr.io/grafana/helm-charts'
    - 'https://kubernetes-sigs.github.io/metrics-server'
    - 'https://slok.github.io/sloth'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
