apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default-project
  namespace: argocd
spec:
  description: Default project
  sourceRepos:
    - 'https://github.com/JimmyChen233/local-monitoring-stack.git'
    - 'https://github.com/JimmyChen233/local-monitoring-stack.git'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'ghcr.io/grafana/helm-charts'
    - 'https://kubernetes-sigs.github.io/metrics-server'
    - 'https://slok.github.io/sloth'
    - 'https://nerdswords.github.io/helm-charts'
    - 'https://traefik.github.io/charts'
    - 'https://charts.bitnami.com/bitnami'
    - 'https://aws.github.io/eks-charts'
    - 'https://jtblin.github.io/kube2iam'
    - 'https://helm.influxdata.com'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
