apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kafka-project
  namespace: argocd
spec:
  description: Kafka project
  sourceRepos:
    - 'https://github.com/JimmyChen233/k8s-dev-254.git'
    - 'https://prometheus-community.github.io/helm-charts'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
