## Default values.yaml for Telegraf
## This is a YAML-formatted file.
## ref: https://hub.docker.com/r/library/telegraf/tags/

replicaCount: 1
image:
  repo: "docker.io/library/telegraf"
  tag: "1.32-alpine"
  pullPolicy: IfNotPresent
podAnnotations: {}
podLabels: {}
imagePullSecrets: []
## Configure args passed to Telegraf containers
args: []
# envFromSecret: "telegraf-tokens"
env:
  - name: HOSTNAME
    value: "telegraf-polling-service"
volumes:
- name: telegraf-probe-script
  configMap:
    name: "telegraf-probe-script"
mountPoints:
- name: telegraf-probe-script
  mountPath: /etc/telegraf/scripts
  subPath: probe_google.sh
resources: {}
# requests:
#   memory: 128Mi
#   cpu: 100m
# limits:
#   memory: 128Mi
#   cpu: 100m
nodeSelector: {}
affinity: {}
tolerations: []
updateStrategy: {}

service:
  enabled: true
  type: ClusterIP
  annotations: {}
rbac:
  # Specifies whether RBAC resources should be created
  create: true
  # Create only for the release namespace or cluster wide (Role vs ClusterRole)
  clusterWide: false
  # Rules for the created rule
  rules: []

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  name:
  annotations: {}

config:
  agent:
    interval: "30s"
    round_interval: true
  outputs:
    - prometheus_client:
        listen: ":9273"
        path: "/metrics"
  inputs:
    - exec:
        commands: ["/etc/telegraf/scripts/probe_google.sh"]
        timeout: "5s"
        data_format: "prometheus"
        name_suffix: "_probe"
        interval: "30s"
metrics:
  health:
    enabled: false
    service_address: "http://:8888"
    threshold: 5000.0
  internal:
    enabled: true
    collect_memstats: false

## Pod disruption budget configuration
##
pdb:
  ## Specifies whether a Pod disruption budget should be created
  ##
  create: true
  minAvailable: 1
  # maxUnavailable: 1

# containerPorts:
# - name: http
#   containerPort: 9273
#   protocol: TCP