
slos:
  - name: "ci-token-creation-latency"
    objective: 99.99
    description: "SLO based on CI access token creation latency."
    sli:
      events:
        errorQuery: |
          sum(count_over_time(ServletRequests_value{component=~"idbroker", responseCodeGroup="5xx", uri="/idb/oauth2/v1/access_token", cluster!="BTS_EU"}[{{.window}}:]))
        totalQuery: |
          sum(count_over_time(ServletRequests_value{component=~"idbroker", uri="/idb/oauth2/v1/access_token", cluster!="BTS_EU"}[{{.window}}:]))
    alerting:
      name: "CITokenCreationLatencyHigh"
      labels:
        team: wbx-ci
      annotations:
        summary: "CI Token Creation Latency is high"
      pageAlert:
        labels:
          severity: pageteam
          routing_key: myteam
        expr: |
          slo:current_burn_rate:ratio{sloth_service="ci-token-creation-latency"} > 1.5
      ticketAlert:
        labels:
          severity: "slack"
          slack_channel: "#alerts-myteam"