
slos:
  - name: "ci-token-creation-latency"
    objective: 99.99
    description: "SLO based on CI access token creation latency."
    sli:
      events:
        errorQuery: |
          sum(count_over_time((email_send_success{job="o365-poc-send-email"}==0)[{{.window}}:])) by(job) or vector(0)
        totalQuery: |
          sum(count_over_time((email_send_success{job="o365-poc-send-email"})[{{.window}}:])) by(job)

    alerting:
      name: "O365EmailSentErrorRate"
      labels:
        category: "availability"
      annotations:
        summary: "O365 email sent error rate is high"
      pageAlert:
        labels:
          severity: pageteam
          routing_key: myteam
        expr: |
          slo:current_burn_rate:ratio{sloth_service="o365-outlook-availability"} > 1.5
      ticketAlert:
        labels:
          severity: "slack"
          slack_channel: "#alerts-myteam"
