slos:
  - name: "backup_connectivity"
    objective: 99.9
    description: "SLO based on availability for the connectivity of commserver and S3 bucket for dprs backup service."
    sli:
      events:
        errorQuery: |
          count_over_time(((time() - aws_s3_backupmetrics_last_backup_time_maximum{dimension_BucketName="dprsbackuptest"})/60 > 7)[{{.window}}])
        totalQuery: |
          count_over_time((aws_s3_backupmetrics_last_backup_time_maximum{dimension_BucketName="dprsbackuptest"})[{{.window}}])

    alerting:
      name: "BackupConnectivityHighErrorRate"
      labels:
        category: "availability"
      annotations:
        summary: "Backup connectivity for S3 bucket 'dprsbackuptest' has exceeded the 7-minute threshold since the last event."
      pageAlert:
        labels:
          severity: pageteam
          routing_key: myteam
        expr: |
          slo:current_burn_rate:ratio{sloth_service="backup_connectivity"} > 1.5
      ticketAlert:
        labels:
          severity: "slack"
          slack_channel: "#alerts-myteam"
