slos:
  - name: "dns_queries_success_tcp"
    objective: 99.999
    description: "SLO based on the DNS queries successfully resolved by vhdns tcp"
    sli:
      events:
        errorQuery: |
          count_over_time(probe_success{job="blackbox", module=~"dns_tcp.*",domain=~".*vhdns.*"} == 0[{{.window}}])
        totalQuery: |
          count_over_time(probe_success{job="blackbox", module=~"dns_tcp.*",domain=~".*vhdns.*"}[{{.window}}])

    alerting:
      page_alert:
        disable: true
      ticket_alert:
        disable: true
