slos:
  - name: "dns_queries_success_tcp_lessthan_250ms"
    objective: 99.999
    description: "SLO based on the DNS queries successfully resolved by vhdns tcp within 250 ms"
    sli:
      events:
        errorQuery: |
          sum by(pod, probe_type) (
            rate(prober_probe_duration_seconds_bucket{
              container="coredns",
              endpoint="https-metrics",
              instance="172.18.0.4:10250",
              job="kubelet",
              pod="coredns-6f6b679f8f-5ncpr",
              probe_type="Liveness",
              service="prometheus-operator-kube-p-kubelet",
              le="0.25"
            }[{{.window}}:])
          )
        totalQuery: |
          sum by(pod, probe_type) (
            rate(prober_probe_duration_seconds_bucket{
              container="coredns",
              endpoint="https-metrics",
              instance="172.18.0.4:10250",
              job="kubelet",
              pod="coredns-6f6b679f8f-5ncpr",
              probe_type="Liveness",
              service="prometheus-operator-kube-p-kubelet",
              le="+Inf"
            }[{{.window}}:])
          )

    alerting:
      annotations:
        summary: >-
          Probe duration for dns_tcp queries has latency higher than 250ms
      labels:
        category: availability
      name: DNSQueriesSuccessTCPLatencyHigh
      pageAlert:
        labels:
          routing_key: myteam
          severity: pageteam
        expr: |
          slo:current_burn_rate:ratio{sloth_service="dns_queries_success_tcp_lessthan_250ms"} > 1.5
      ticketAlert:
        labels:
          severity: slack
          slack_channel: '#alerts-myteam'
