---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero-config
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: velero-config
  chart:
    spec:
      chart: ./manifests/velero/helm/velero-config
      sourceRef:
        kind: GitRepository
        name: k8s-local-dev
        namespace: flux-system
      interval: 5m0s
      reconcileStrategy: Revision
  valuesFrom:
  - kind: ConfigMap
    name: dsh-platform-config
    valuesKey: values.yaml
