---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  interval: 5m0s
  targetNamespace: velero
  releaseName: velero
  chart:
    spec:
      chart: velero
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 5m0s
  dependsOn: 
    - name: velero-config
  valuesFrom:
  - kind: ConfigMap
    name: velero-config
    valuesKey: values.yaml
