deployment:
  replicas: 1
service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use Network Load Balancer (NLB)
    service.beta.kubernetes.io/aws-load-balancer-eip-allocations: "eipalloc-0b1406114dcd7d6d0,eipalloc-0250992e7fb5b9cc3"