#1
ports:
  web:
    expose:
      default: true
    port: 8000
    protocol: TCP
  websecure:
    port: 8443
    expose: 
      default: true
    exposedPort: 443
    protocol: TCP
    tls:
      enabled: false
  traefik:
    port: 9000
    expose: 
      default: true
    exposedPort: 9000
    protocol: TCP
    tls:
      enabled: false
  prometheus:
    port: 9090
    expose: 
      default: true
    exposedPort: 9090
    protocol: TCP

#2
ingressRoute:
  dashboard:
    enabled: false
deployment:
  replicas: 1
service:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: traefik.localmonitoringstack.com.au
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443, 9000"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-southeast-2:975050172027:certificate/c920a253-65b1-4c4c-99e6-963f43e3beee
    service.beta.kubernetes.io/load-balancer-source-ranges: 0.0.0.0/0
globalArguments:
  - "--api.insecure=true"
providers:
  kubernetesIngress:
    enabled: true
    ingressClass: traefik
logs:
  general:
    level: DEBUG
  access:
    enabled: true