apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: zookeeper
  serviceName: "zookeeper"
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: zookeeper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 2181
              name: client
