---
apiVersion: v1
kind: ConfigMap
metadata:
  name: all-tests
  namespace: {{ $.Values.namespace }}
data:
{{- range $file, $_ := .Files.Glob "tests/**.yaml" }}
  {{ $file | base | trimSuffix ".yaml" }}.yaml: |
    {{- $.Files.Get $file | nindent 4 }}
{{- end }}
