---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.release }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.release }}
  template:
    metadata:
      labels:
        app: {{ .Values.release }}
    spec:
      containers:
        - name: {{ .Values.release }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: POLL_INTERVAL
              value: "{{ .Values.pollInterval }}"
          envFrom:
            - secretRef:
                name: playwright-credentials
          volumeMounts:
            - name: testfile-volume
              mountPath: /app/tests
      volumes:
        - name: testfile-volume
          configMap:
            name: all-tests
