apiVersion: v1
kind: Service
metadata:
  name: prometheus-playwright
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus-playwright
spec:
  selector:
    app: prometheus-playwright
  ports:
    - protocol: TCP
      port: 8080        # Service port
      targetPort: 8080  # Container port
