apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.release }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.release }}
spec:
  selector:
    app: {{ .Values.release }}
  ports:
    - protocol: TCP
      port: 8080        # Service port
      targetPort: 8080  # Container port
