{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.release }}
  namespace: {{ .Values.namespace }}
  labels:
    release: {{ .Values.servicemonitor.release }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.release }}
  endpoints:
    - port: "8080"
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
{{- end }}
