replicaCount: 1

image:
  repository: telegraf
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9273
  annotations: {}
  labels: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  telegrafConf: |
    [agent]
      interval = "5m"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = false
      quiet = false
      logfile = ""

    [[inputs.exec]]
      commands = ["/tmp/ping_script.sh"]
      timeout = "5s"
      data_format = "prometheus"
      name_suffix = "_ping"

    [[outputs.prometheus_client]]
      listen = ":9273"
      path = "/metrics"
      expiration_interval = "60m"
      collectors_exclude = ["gocollector", "process"]
