
---
apiVersion: batch/v1
kind: Job
metadata:
  {{$nameSuffix := printf "%s" .Values.images.alpineK8S | sha256sum | substr 0 12 -}}
  {{ if .Values.platform.veleroRestoreEnabled -}}
  name: velero-restore-v7-{{ $nameSuffix }}
  {{ else -}}
  name: velero-dummy-restore-v7-{{ $nameSuffix }}
  {{ end -}}
  namespace: velero
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 200
  template:
    spec:
      serviceAccountName: velero-restore-init
      restartPolicy: OnFailure
      containers:
      - name: backup-restore
        command: 
        - bash
        - '-e'
        - '-c'
        - |
          {{ if .Values.platform.veleroRestoreEnabled }}
          python /script/velero-restore.py
          {{ else }}
          python /script/velero-restore.py dummyrestore
          {{ end }}
        image: {{ .Values.images.alpineK8S }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 512Mi
        volumeMounts:
        - mountPath: /script
          name: velero-restore
        - mountPath: /namespaces
          name: velero-namespaces
        - mountPath: /secrets
          name: velero-secrets
        - mountPath: /certs
          name: velero-certs
        - mountPath: /pvc
          name: velero-pvc
        - mountPath: /kafkaclusters
          name: velero-kafkaclusters
        - mountPath: /configmaps
          name: velero-configmaps
        - mountPath: /pgclusters
          name: velero-pgclusters
        - mountPath: /empty-restore
          name: velero-empty-restore
        - mountPath: /empty-backup
          name: velero-empty-backup
      volumes:
      - name: velero-restore
        configMap:
          name: velero-restore
      - name: velero-namespaces
        configMap:
          name: velero-namespaces
      - name: velero-secrets
        configMap:
          name: velero-secrets
      - name: velero-certs
        configMap:
          name: velero-certs
      - name: velero-pvc
        configMap:
          name: velero-pvc
      - name: velero-kafkaclusters
        configMap:
          name: velero-kafkaclusters
      - name: velero-configmaps
        configMap:
          name: velero-configmaps
      - name: velero-pgclusters
        configMap:
          name: velero-pgclusters
      - name: velero-empty-restore
        configMap:
          name: velero-empty-restore
      - name: velero-empty-backup
        configMap:
          name: velero-empty-backup
