apiVersion: v1
kind: Service
metadata:
  name: stateful-blackbox-exporter
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
  selector:
    app: stateful-blackbox-exporter
