apiVersion: v1
data:
  values.yaml: "platform:\n  \"allowAllTenantEgress\": true\n  \"aws\":\n    \"RDSIPs\":
    []\n    \"accountId\": \"242311456376\"\n    \"eip_subnet_id\": \"1\"\n    \"hostedPrivateZoneId\":
    \"Z06293351LBVVE0FBDVZU\"\n    \"hostedZoneId\": \"Z02166652Q1RR2PA19Y83\"\n    \"iamPermissionBoundary\":
    \"arn:aws:iam::242311456376:policy/kpn-permissions-boundary\"\n    \"iamUserTags\":
    \"{'KPNUser': 'SystemUser'}\"\n    \"mqttEipAz1\": \"eipalloc-026f010765d3da002\"\n
    \   \"mqttEipAz2\": \"eipalloc-04026326484b0d3ff\"\n    \"mqttEipAz3\": \"eipalloc-0ce2e3fc05428e5d7\"\n
    \   \"nlb_subnets\": \"subnet-0466e528e9ae0958f\"\n    \"podSubnetCIDR\":\n    -
    \"100.80.0.0/16\"\n    - \"100.81.0.0/16\"\n    - \"100.82.0.0/16\"\n    \"privateSubnetCIDR\":\n
    \   - \"10.28.80.0/20\"\n    - \"10.28.96.0/20\"\n    - \"10.28.112.0/20\"\n    \"publicSubnetCIDR\":\n
    \   - \"10.28.64.0/22\"\n    - \"10.28.68.0/22\"\n    - \"10.28.72.0/22\"\n    \"region\":
    \"eu-west-1\"\n    \"traefikEipAz1\": \"eipalloc-04fd076b11c28e978\"\n    \"traefikEipAz2\":
    \"eipalloc-0dc79e9623da1f3c4\"\n    \"traefikEipAz3\": \"eipalloc-0a3eeeeb8dff5b2b6\"\n
    \   \"vpcId\": \"vpc-04e8ed635809e4a2c\"\n  \"backupBucket\": \"s3://environment-k8s-dev-aws-lz-dsh\"\n
    \ \"billingTags\":\n    \"kpn:application\": \"k8s-dev-aws-lz-dsh\"\n    \"kpn:cost-center\":
    \"89409\"\n    \"kpn:environment\": \"non-production\"\n    \"kpn:environment-type\":
    \"k8s-dev\"\n    \"kpn:kpn-theme\": \"data office\"\n    \"kpn:product\": \"DSH
    NONPROD K8S LZ\"\n    \"kpn:product-owner\": \"a.j.oosterveld@kpn.com\"\n    \"kpn:team-owner\":
    \"dsh@kpn.com\"\n  \"clusterIssuerPublic\": \"letsencrypt-prod\"\n  \"ctestEnabled\":
    true\n  \"dexRelease\":\n    \"tag\": \"dsh-latest\"\n  \"dnsDomain\": \"dev.dsh-k8s.np.aws.kpn.com\"\n
    \ \"dnsIngressClass\": \"traefik\"\n  \"dnsPrivateDomain\": \"dev.dsh-k8s.np.aws.kpn.org\"\n
    \ \"dnsPrivateIngressClass\": \"traefik-internal\"\n  \"dnsPrivateZone\": \"dsh-k8s.np.aws.kpn.org\"\n
    \ \"dnsZone\": \"dsh-k8s.np.aws.kpn.com\"\n  \"enableDataCatalog\": true\n  \"enableDexDeveloper\":
    true\n  \"enableVpn\": true\n  \"environmentsBucket\": \"environment-k8s-dev-aws-lz-dsh\"\n
    \ \"kafkaStorageClass\": \"kafka-v4\"\n  \"kafkaVolumeSize\": \"500Gi\"\n  \"kafkaZookeeperChroot\":
    \"/kafka/tt\"\n  \"keycloak\":\n    \"realm\": \"k8s-dev-aws-lz-dsh\"\n  \"lokiBucket\":
    \"loki-k8s-dev-aws-lz-dsh\"\n  \"lokiSystemBucket\": \"loki-system-k8s-dev-aws-lz-dsh\"\n
    \ \"lz\": true\n  \"maintenanceMode\": false\n  \"mimirBucket\": \"mimir-k8s-dev-aws-lz-dsh\"\n
    \ \"mirrors\": {}\n  \"name\": \"k8s-dev-aws-lz-dsh\"\n  \"netmask\": \"255.255.0.0\"\n
    \ \"numKafkaBrokers\": 3\n  \"oidcEndpoint\": \"https://auth.staging.cp.kpn-dsh.com/auth/realms\"\n
    \ \"overrides\":\n    \"authenticator_cpu\": \"100m\"\n    \"authenticator_memory\":
    \"2Gi\"\n    \"authenticator_replicas\": 2\n    \"httpProtocolAdapter_cpu\": \"100m\"\n
    \   \"httpProtocolAdapter_memory\": \"2Gi\"\n    \"httpProtocolAdapter_replicas\":
    2\n    \"kongIngressController_cpu\": \"125m\"\n    \"kongIngressController_memory\":
    \"512Mi\"\n    \"kong_cpu\": \"125m\"\n    \"kong_memory\": \"512Mi\"\n    \"kong_replicas\":
    2\n    \"mqttProtocolAdapter_cpu\": \"100m\"\n    \"mqttProtocolAdapter_memory\":
    \"2Gi\"\n    \"mqttProtocolAdapter_replicas\": 0\n    \"mqttsProtocolAdapter_replicas\":
    2\n    \"prometheus_replicas\": 2\n    \"prov_datacatalog_replicas\": 1\n    \"sessionTracker_cpu\":
    \"500m\"\n    \"sessionTracker_memory\": \"1536Mi\"\n    \"sessionTracker_replicas\":
    2\n    \"sslproxy_cpu\": \"500m\"\n    \"sslproxy_memory\": \"2Gi\"\n    \"sslproxy_replicas\":
    0\n    \"topicTracker_cpu\": \"500m\"\n    \"topicTracker_memory\": \"2Gi\"\n
    \   \"topicTracker_replicas\": 2\n    \"traefikInternal_cpu\": \"200m\"\n    \"traefikInternal_memory\":
    \"256Mi\"\n    \"traefikInternal_replicas\": 2\n    \"traefik_cpu\": \"200m\"\n
    \   \"traefik_memory\": \"256Mi\"\n    \"traefik_replicas\": 2\n    \"userTracker_cpu\":
    \"375m\"\n    \"userTracker_memory\": \"2Gi\"\n    \"userTracker_replicas\": 2\n
    \ \"platformStatusUrl\": \"\"\n  \"postgresBackupBucket\": \"postgres-k8s-dev-aws-lz-dsh\"\n
    \ \"release\":\n    \"tag\": \"dsh-latest\"\n  \"schemaregistryDatabaseBackupGeneration\":
    1\n  \"serviceNetwork\": \"10.142.0.0\"\n  \"sslProxyToMqttAdapterMapping\":\n
    \ - \"adapterPorts\":\n    - \"1883\"\n    - \"1884\"\n    - \"1885\"\n    - \"1886\"\n
    \   - \"1887\"\n    - \"1888\"\n    - \"1889\"\n    - \"1890\"\n    \"name\":
    \"MQTT\"\n    \"proxyPorts\":\n    - \"8883\"\n  - \"adapterPorts\":\n    - \"8080\"\n
    \   - \"8081\"\n    \"name\": \"MQTTWS\"\n    \"proxyPorts\":\n    - \"443\"\n
    \   - \"8443\"\n  \"tempoBucket\": \"tempo-k8s-dev-aws-lz-dsh\"\n  \"tenantCustomEgress\":\n
    \   \"connector-library\":\n      \"tcp\":\n      - 1605\n    \"gdh-mnemonic-01\":\n
    \     \"tcp\":\n      - 1514\n      - 1537\n      - 1544\n      - 1601\n      -
    1605\n  \"tenantDefaultEgress\":\n    \"tcp\":\n    - 22\n    - 53\n    - 443\n
    \   - 1883\n    - 8443\n    - 8883\n    - 9091\n    - 20\n    - 21\n    - 25\n
    \   - 80\n    - 1025\n    - 1433\n    - 5432\n    - 9092\n    - 9093\n    \"udp\":\n
    \   - 53\n    - 123\n    - 1434\n  \"thanosBucket\": \"thanos-k8s-dev-aws-lz-dsh\"\n
    \ \"veleroRestoreEnabled\": true\n  \n"
kind: ConfigMap
metadata:
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: dsh-platform-config
  namespace: flux-system
