apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: telegraf
data:
  telegraf.conf: |
{{ .Values.config.telegrafConf | nindent 4 }}

  ping_script.sh: |
{{ (.Files.Get "scripts/ping_script.sh") | nindent 4 }}