apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: telegraf
data:
  telegraf.conf: |
    {{ .Values.config.telegrafConf | indent 4 }}

  ping_script.sh: |
    #!/bin/bash
    ping_time=$(ping -c 1 google.com | grep 'time=' | awk -F'time=' '{print $2}' | awk '{print $1}')
    if [ -z "$ping_time" ]; then
      ping_time=-1
    fi
    echo "# HELP ping_response_time_seconds Response time of ping to google.com"
    echo "# TYPE ping_response_time_seconds gauge"
    echo "ping_response_time_seconds $ping_time"
