apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: telegraf
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      initContainers:
        - name: init-script
          image: busybox
          command: [ "sh", "-c" ]
          args:
            - cp /scripts/ping_script.sh /tmp/ping_script.sh && chmod +x /tmp/ping_script.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      containers:
        - name: telegraf
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
            - name: scripts
              mountPath: /scripts
          ports:
            - containerPort: 9273
      volumes:
        - name: config
          configMap:
            name: telegraf-config
            items:
              - key: telegraf.conf
                path: telegraf.conf
        - name: scripts
          configMap:
            name: telegraf-config
            items:
              - key: ping_script.sh
                path: ping_script.sh
