apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-probe-script
  namespace: {{ .Values.namespace }}
data:
  probe_google.sh: |
    #!/bin/bash
    if curl -s --head --request GET https://www.google.com | grep "200 OK" > /dev/null; then
      echo "# HELP probe_success Probing result for google.com"
      echo "# TYPE probe_success gauge"
      echo "probe_success 1"
    else
      echo "# HELP probe_success Probing result for google.com"
      echo "# TYPE probe_success gauge"
      echo "probe_success 0"
    fi
