apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
  namespace: telegraf
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 9273
      targetPort: 9273
      protocol: TCP
  selector:
    app: {{ .Release.Name }}
