apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-certificate
  namespace: cert-manager
spec:
  secretName: test-certificate-secret
  issuerRef:
    name: letsencrypt-issuer
  duration: 48h
  renewBefore: 24h
  commonName: example.com
  dnsNames:
    - example.com
