apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-leaderelection
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-leaderelection
subjects:
- kind: ServiceAccount
  name: default
  namespace: cert-manager
roleRef:
  kind: ClusterRole
  name: cert-manager-leaderelection
  apiGroup: rbac.authorization.k8s.io
