replicaCount: 1

image:
  repository: banzaicloud/kafka-operator
  tag: v0.25.1
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
