aws:
  zoneType: public   # Can be 'public' or 'private' for your Route 53 zone type
  region: ap-southeast-2

provider: aws
registry: txt
interval: 1m
txt-owner-id: external-dns

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::975050172027:role/ExternalDNSRole
  name: external-dns

rbac:
  create: true
  pspEnabled: false

sources:
  - service
  - ingress
