apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default-project
  sources:
    - repoURL: 'https://github.com/JimmyChen233/local-monitoring-stack.git'
      targetRevision: main
      ref: values
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 9.0.0
      chart: prometheus-blackbox-exporter
      helm:
        valueFiles:
        - $values/ArgoCD/apps/blackbox-exporter/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Validate=false
