apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default-project
  sources:
    - repoURL: 'https://github.com/JimmyChen233/k8s-dev-254.git'
      targetRevision: HEAD
      ref: values
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 0.25.3
      chart: prometheus-cloudwatch-exporter
      helm:
        valueFiles:
        - $values/ArgoCD/apps/cloudwatch-exporter/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Validate=false
