apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudwatch-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default-project
  sources:
    - repoURL: 'https://github.com/JimmyChen233/local-monitoring-stack.git'
      targetRevision: demo
      ref: values
    - repoURL: https://nerdswords.github.io/helm-charts
      targetRevision: 0.38.0
      chart: yet-another-cloudwatch-exporter
      helm:
        valueFiles:
        - $values/ArgoCD/apps/cloudwatch-exporter/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Validate=false
