apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crds
  namespace: argocd
spec:
  project: default-project
  source:
    repoURL: 'https://github.com/JimmyChen233/local-monitoring-stack.git'
    targetRevision: HEAD
    path: 'ArgoCD/CRD'
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
