apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  project: default-project
  sources:
    - repoURL: 'https://github.com/clear-route/local-monitoring-stack.git'
      targetRevision: demo
      ref: values
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      targetRevision: 1.14.5
      chart: external-dns
      helm:
        valueFiles:
        - $values/ArgoCD/apps/external-dns/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: network
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
