apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-mimir
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/clear-route/local-monitoring-stack.git'
      targetRevision: demo
      ref: values
    - repoURL: https://grafana.github.io/helm-charts
      chart: mimir-distributed
      targetRevision: 5.5.0-weekly.309
      helm:
        valueFiles:
        - $values/ArgoCD/apps/grafana-mimir/files/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mimir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
