apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-operator
  namespace: argocd
spec:
  project: kafka-project
  source:
    repoURL: 'https://github.com/JimmyChen233/local-monitoring-stack.git'
    targetRevision: HEAD
    path: 'ArgoCD/apps/koperator'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
