apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube2iam
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default-project
  sources:
    - repoURL: 'https://github.com/JimmyChen233/local-monitoring-stack.git'
      targetRevision: main
      path: 'ArgoCD/apps/kube2iam'
      ref: values
    - repoURL: https://jtblin.github.io/kube2iam
      targetRevision: 2.6.0
      chart: kube2iam/kube2iam
      helm:
        valueFiles:
        - $values/ArgoCD/apps/kube2iam/files/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Validate=false
