apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-application
  namespace: argocd
spec:
  project: kafka-project
  source:
    repoURL: 'https://github.com/your-username/your-repo.git'
    targetRevision: HEAD
    path: 'ArgoCD/namespaces'
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
