apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-application
  namespace: argocd
spec:
  project: default-project
  source:
    repoURL: 'https://github.com/clear-route/local-monitoring-stack.git'
    targetRevision: HEAD
    path: 'ArgoCD/namespaces'
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
