apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  project: kafka-project
  sources:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 25.26.0
    chart: kube-prometheus-stack 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
