apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default-project
  sources:
    - repoURL: 'https://github.com/JimmyChen233/k8s-dev-254.git'
      targetRevision: HEAD
      ref: values
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 61.8.0
      chart: kube-prometheus-stack
      helm:
        valueFiles:
        - $values/ArgoCD/apps/prometheus-operator/values.yaml
    - repoURL: https://kubernetes-sigs.github.io/metrics-server
      targetRevision: 0.6.4
      chart: metrics-server
      helm:
        valueFiles:
        - $values/ArgoCD/apps/prometheus-operator/metrics-server/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Validate=false
