apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  project: kafka-project
  sources:
    - repoURL: 'https://github.com/JimmyChen233/k8s-dev-254.git'
      targetRevision: HEAD
      path: 'ArgoCD/apps/prometheus-operator'
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: kube-prometheus-stack
      targetRevision: "61.7.1"
      helm:
        valuesFrom:
          - configMapKeyRef:
              name: prometheus-operator-config
              key: values.yaml
    
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
