apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default-project
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 61.8.0
    chart: kube-prometheus-stack 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
