apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default-project
  sources:
    - repoURL: 'https://github.com/clear-route/local-monitoring-stack.git'
      targetRevision: HEAD
      ref: values
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 61.8.0
      chart: kube-prometheus-stack
      helm:
        valueFiles:
        - $values/ArgoCD/apps/prometheus-operator/files/prometheus-operator-config.yaml
    - repoURL: https://kubernetes-sigs.github.io/metrics-server
      targetRevision: 3.12.1
      chart: metrics-server
      helm:
        valueFiles:
        - $values/ArgoCD/apps/prometheus-operator/files/metrics-server-config.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Validate=false
