apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sloth
  namespace: argocd
spec:
  project: default-project
  sources:
    - repoURL: 'https://github.com/clear-route/local-monitoring-stack.git'
      targetRevision: demo
      path: 'ArgoCD/apps/sloth'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "monitoring"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
