apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sloth
  namespace: argocd
spec:
  project: default-project
  sources:
    - repoURL: 'https://github.com/clear-route/local-monitoring-stack.git'
      targetRevision: add-sloth
      ref: values
    - repoURL: "https://slok.github.io/sloth"
      targetRevision: 0.7.0
      chart: "sloth"
      helm:
        valueFiles:
        - $values/ArgoCD/apps/sloth/files/sloth-config.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "monitoring"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
