apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default-project
  sources:
    - repoURL: 'https://github.com/clear-route/local-monitoring-stack.git'
      targetRevision: demo
      ref: values
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: v31.1.0
      helm:
        valueFiles:
        - $values/ArgoCD/apps/traefik/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
