{{- range $path, $_ := .Files.Glob "slos/**.yaml" }}
---
apiVersion: sloth.slok.dev/v1
kind: PrometheusServiceLevel
metadata:
  {{- $servicename := $path | base | trimSuffix ".yaml" }}
  name: sloth-slo-{{ printf "%s" $servicename | trunc 63 }}
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  service: "{{ $servicename }}"
  {{- with $.Files.Get $path | fromYaml }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
