apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudreve
  namespace: cloudreve
spec:
  selector:
    matchLabels:
      app: cloudreve
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudreve
    spec:
      containers:
        - name: cloudreve
          image: {{ .Values.cloudreve.image }}
          ports:
            - containerPort: 5212
          volumeMounts:
            - name: temp-data
              mountPath: /data
            - name: cloudreve-storage
              mountPath: /cloudreve/uploads
              subPath: uploads
            - name: cloudreve-storage
              mountPath: /cloudreve/conf.ini
              subPath: conf.ini
            - name: cloudreve-storage
              mountPath: /cloudreve/avatar
              subPath: avatar
      volumes:
        - name: cloudreve-storage
          persistentVolumeClaim:
            claimName: cloudreve-pvc
        - name: temp-data
          persistentVolumeClaim:
            claimName: temp-data-pvc
