---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: cloudreve
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
