---
apiVersion: v1
kind: Service
metadata:
  name: cloudreve
  namespace: cloudreve
spec:
  ports:
  - port: 5212
    targetPort: 5212
  selector:
    app: cloudreve
---
apiVersion: v1
kind: Service
metadata:
  name: aria2
  namespace: cloudreve
spec:
  ports:
  - port: 6800
    targetPort: 6800
  selector:
    app: aria2
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: cloudreve
spec:
  selector:
    app: redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
