---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aria2-config-pvc
  namespace: cloudreve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.aria2.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: temp-data-pvc
  namespace: cloudreve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tempdata.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloudreve-pvc
  namespace: cloudreve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cloudreve.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: cloudreve
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
