apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-operator
  labels:
    app: kafka-operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kafka-operator
  template:
    metadata:
      labels:
        app: kafka-operator
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: kafka-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
