apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring
type: Opaque
data:
  additional-scrape-configs.yaml: |
{{ .Files.Get "files/additional-scrape-config.yaml" | b64enc | indent 4 }}
