apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    grafana-type: cp-grafana
spec:
  config:
    auth:
      disable_login_form: false
      disable_signout_menu: true
    log:
      mode: console
    security:
      admin_user: "admin"
      admin_password: "grafana-operator"
