apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web 
    external-dns.alpha.kubernetes.io/hostname: "prometheus.localmonitoringstack.com.au"
spec:
  rules:
  - host: prometheus.localmonitoringstack.com.au
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-operator-kube-p-prometheus       # Name of your Prometheus service
            port:
              number: 9090               # Port on which Prometheus is exposed
