apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingressroute
  namespace: monitoring
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "prometheus.localmonitoringstack.com.au"
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: prometheus-operator-kube-p-prometheus
          port: 9090
  