---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m0s
  targetNamespace: monitoring
  releaseName: prometheus
  dependsOn:
    - name: prometheus-configuration
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '55.6.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 1h
  install:
    crds: Skip
    remediation:
      retries: -1
  upgrade:
    crds: Skip
    remediation:
      retries: -1
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-operator-config
      valuesKey: values.yaml
    - kind: Secret
      name: monitoring-grafana
      targetPath: keycloakClientSecret
      valuesKey: keycloakClientSecret
    - kind: Secret
      name: monitoring-grafana
      targetPath: signingSecret
      valuesKey: signingSecret
    - kind: ConfigMap
      name: prometheus-helm-overrides
      optional: true
