apiVersion: velero.io/v1
kind: Restore
metadata:
  labels:
  name: restore-namespaces
  namespace: velero
spec:
  scheduleName: backup-base
  backupName: ""
  includedResources:
    - namespaces
  excludedNamespaces:
    - flux-system
    - kube
    - kube-system

