---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-work
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/JimmyChen233/k8s-dev-254.git
  ref:
    branch: main
  secretRef:
    name: gitcredentials
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: prometheus-repo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://prometheus-community.github.io/helm-charts
  ref:
    branch: main